import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import {
  validateSkillName,
  checkRecurrenceGate,
  checkVerificationGate,
  checkGeneralizationGate,
  extractSkill,
} from "../scripts/extract-skill";

describe("Skill Extraction Helper (extract-skill)", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "muse-skill-extract-test-"));
  });

  afterEach(() => {
    if (fs.existsSync(tmpDir)) {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test("validates skill name format strictly as kebab-case", () => {
    expect(validateSkillName("valid-skill-name")).toBe(true);
    expect(validateSkillName("skill123")).toBe(true);
    expect(validateSkillName("multi-part-skill-name")).toBe(true);

    expect(validateSkillName("InvalidName")).toBe(false);
    expect(validateSkillName("snake_case_skill")).toBe(false);
    expect(validateSkillName("-starting-dash")).toBe(false);
    expect(validateSkillName("ending-dash-")).toBe(false);
    expect(validateSkillName("double--dash")).toBe(false);
  });

  test("Gate 1: Recurrence Gate enforces >= 3 occurrences", () => {
    // Under threshold
    const failRes = checkRecurrenceGate(undefined, 2, false);
    expect(failRes.ok).toBe(false);
    expect(failRes.message).toContain("Pattern recurrence count (2) < 3");

    // Meets threshold
    const passRes = checkRecurrenceGate(undefined, 3, false);
    expect(passRes.ok).toBe(true);

    // Bypasses with force
    const forceRes = checkRecurrenceGate(undefined, 1, true);
    expect(forceRes.ok).toBe(true);

    // Parses from evidence file
    const evidenceFile = path.join(tmpDir, "LEARNINGS.md");
    fs.writeFileSync(
      evidenceFile,
      "- [x] Occurrence 1: Observed in API auth\n- [x] Occurrence 2: Observed in worker\n- [x] Occurrence 3: Observed in cron\n"
    );
    const fileRes = checkRecurrenceGate(evidenceFile, undefined, false);
    expect(fileRes.ok).toBe(true);
  });

  test("Gate 2: Verification Gate enforces tested solutions", () => {
    // Unverified fails
    const failRes = checkVerificationGate(undefined, false, false);
    expect(failRes.ok).toBe(false);
    expect(failRes.message).toContain("Solution is not verified");

    // Explicitly verified succeeds
    const passRes = checkVerificationGate(undefined, true, false);
    expect(passRes.ok).toBe(true);

    // Passing command succeeds
    const cmdPass = checkVerificationGate("true", false, false, tmpDir);
    expect(cmdPass.ok).toBe(true);

    // Failing command fails
    const cmdFail = checkVerificationGate("false", false, false, tmpDir);
    expect(cmdFail.ok).toBe(false);
    expect(cmdFail.message).toContain("Verification command failed");

    // Force bypass
    const forceRes = checkVerificationGate(undefined, false, true);
    expect(forceRes.ok).toBe(true);
  });

  test("Gate 3: Generalization Gate rejects hardcoded user paths and secrets", () => {
    // Hardcoded home path
    const pathFail = checkGeneralizationGate(["Audit user /home/alice/project for leaks"]);
    expect(pathFail.ok).toBe(false);
    expect(pathFail.message).toContain("Hardcoded Linux home directory detected");

    // Hardcoded secret
    const secretFail = checkGeneralizationGate(["Connect using key sk-1234567890abcdef123456"]);
    expect(secretFail.ok).toBe(false);
    expect(secretFail.message).toContain("Potential credential/secret detected");

    // Clean inputs pass
    const cleanPass = checkGeneralizationGate([
      "extract-skill",
      "Universal pattern extractor for automated workflows",
    ]);
    expect(cleanPass.ok).toBe(true);

    // Force bypass
    const forcePass = checkGeneralizationGate(["/home/user/path"], true);
    expect(forcePass.ok).toBe(true);
  });

  test("scaffolds a fully RFC-compliant skill directory structure", () => {
    const destDir = path.join(tmpDir, "auto-test-skill");

    const result = extractSkill({
      name: "auto-test-skill",
      desc: "Deterministic test skill generated by automated extraction helper.",
      occurrences: 3,
      verified: true,
      dest: destDir,
      tags: ["testing", "automation"],
      tools: ["bash", "view_file"],
      cwd: tmpDir,
    });

    expect(result.success).toBe(true);
    expect(fs.existsSync(path.join(destDir, "SKILL.md"))).toBe(true);
    expect(fs.existsSync(path.join(destDir, "README.md"))).toBe(true);
    expect(fs.existsSync(path.join(destDir, "agents", "openai.yaml"))).toBe(true);

    const skillContent = fs.readFileSync(path.join(destDir, "SKILL.md"), "utf8");

    // Check RFC sections
    expect(skillContent).toContain("## When to Use");
    expect(skillContent).toContain("## Quick Reference");
    expect(skillContent).toContain("## Procedure");
    expect(skillContent).toContain("## Pitfalls");
    expect(skillContent).toContain("## Verification");

    // Check frontmatter
    expect(skillContent).toContain("name: auto-test-skill");
    expect(skillContent).toContain("version: 1.0.0");
    expect(skillContent).toContain("license: MIT");
    expect(skillContent).toContain("platforms: [macos, linux, windows]");
    expect(skillContent).toContain("metadata:");
    expect(skillContent).toContain("requires_tools: [bash, view_file]");

    // Check companion yaml
    const yamlContent = fs.readFileSync(path.join(destDir, "agents", "openai.yaml"), "utf8");
    expect(yamlContent).toContain("name: auto-test-skill");
    expect(yamlContent).toContain("tools:");
    expect(yamlContent).toContain("instructions:");
  });

  test("dry-run does not write files to disk", () => {
    const destDir = path.join(tmpDir, "dry-run-skill");

    const result = extractSkill({
      name: "dry-run-skill",
      desc: "Simulated skill extraction.",
      occurrences: 4,
      verified: true,
      dest: destDir,
      dryRun: true,
      cwd: tmpDir,
    });

    expect(result.success).toBe(true);
    expect(fs.existsSync(destDir)).toBe(false);
  });

  test("registers new skill into skills.json, llms.txt, and README.md", () => {
    // Initialize mock registry files
    const skillsJsonPath = path.join(tmpDir, "skills.json");
    const llmsTxtPath = path.join(tmpDir, "llms.txt");
    const readmePath = path.join(tmpDir, "README.md");

    fs.writeFileSync(skillsJsonPath, JSON.stringify({ skills: [] }, null, 2));
    fs.writeFileSync(llmsTxtPath, "# LLMS\n\n## Skills\n");
    fs.writeFileSync(
      readmePath,
      "# Catalog\n\n| Skill | Description |\n|:---|:---|\n"
    );

    const result = extractSkill({
      name: "registered-pattern",
      desc: "Skill that gets registered automatically in catalogs.",
      occurrences: 3,
      verified: true,
      dest: path.join(tmpDir, "registered-pattern"),
      register: true,
      cwd: tmpDir,
    });

    expect(result.success).toBe(true);
    expect(result.registered.skillsJson).toBe(true);
    expect(result.registered.llmsTxt).toBe(true);
    expect(result.registered.readme).toBe(true);

    const updatedJson = JSON.parse(fs.readFileSync(skillsJsonPath, "utf8"));
    expect(updatedJson.skills.length).toBe(1);
    expect(updatedJson.skills[0].name).toBe("registered-pattern");

    const updatedLlms = fs.readFileSync(llmsTxtPath, "utf8");
    expect(updatedLlms).toContain("- [registered-pattern]");

    const updatedReadme = fs.readFileSync(readmePath, "utf8");
    expect(updatedReadme).toContain("registered-pattern");
  });
});
